### PR TITLE
Add minimal support for ROS2

### PR DESCRIPTION
**Pull request by gonzalocasas**
This PR builds up on https://github.com/gramaziokohler/roslibpy/pull/120 but makes it a non-breaking change instead. Added ROS2 to the CI tests also, although only testing one tiny part of ROS2 so far.

### What type of change is this?

- [ ] Bug fix in a **backwards-compatible** manner.
- [x] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I added a line to the `CHANGELOG.rst` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [x] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [ ] I ran lint on my computer and there are no errors (i.e. `invoke check`).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by gonzalocasas** [comment]
@iliabaranov I've moved your fix to a `roslibpy.ros2.Header` class and now everything seems to work on both ROS1 and ROS2. I will merge and cut a new release with this.

**Comment by iliabaranov** [comment]
Cheers, thanks! :D

**Comment by gonzalocasas** [comment]
I'll try to add actionlib support soon and fix the rest of the tests

**Comment by gonzalocasas** [comment]
Please let me know if you encounter any issues in the meantime

**Pull request merged**
