### PR TITLE
Add IronPython support

### PR DESCRIPTION
**Pull request by gonzalocasas**
Added support for IronPython by creating a separate implementation of the websocket layer that relies on .NET infrastructure instead of Autobahn (which is hardly installable on IronPython).

Also isolated the event loop management into platform-specific classes to remove all dependencies to Autobahn/Twisted.

### CODE REVIEW

**Comment by gonzalocasas** [comment]
@ipa-mdl hi! perhaps you are interested in checking this out. I merged your change back into this branch and added the exact same behavior to the .NET implementation: https://github.com/gramaziokohler/roslibpy/pull/3/commits/3def6a2ff1cd1885774647862c0f93f79787e415

**Comment by gonzalocasas** [comment]
@Kathrin3010: maybe you're also interested in this one?

**Comment by Kathrin3010** [comment]
yes, for gh certainly, thanks!

**Comment by romanarust** [comment]
1) The README needs to be updated of how to install rospylib with ironpython. Ideally add also an info to use future's print_function if using the library with ironpython 2.7.
2) I get an error in "....\roslibpy\comm\comm_cli.py", line 51, in receive_chunk_async if running [this code](https://gist.github.com/romanarust/1a9ff8756fec328ecaf1bc9e4f97ed84) with ipy, which I don't get with python.

**Comment by gonzalocasas** [comment]
@romanarust thanks! I pushed a fix updates to fix your findings, I tested with a different test case, but I believe it should work now. I also tested the pip install under IronPython and now it works.

**Pull request merged**
