### PR TITLE
Fix Python 2.7 syntax

### PR DESCRIPTION
**Pull request by gonzalocasas**
Pull Request https://github.com/gramaziokohler/roslibpy/pull/105 introduced syntax that is not compatible with Python 2.7 / IronPython.

### What type of change is this?

- [x] Bug fix in a **backwards-compatible** manner.
- [ ] New feature in a **backwards-compatible** manner.
- [ ] Breaking change: bug fix or new feature that involve incompatible API changes.
- [ ] Other (e.g. doc update, configuration, etc)

### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I added a line to the `CHANGELOG.rst` file in the `Unreleased` section under the most fitting heading (e.g. `Added`, `Changed`, `Removed`).
- [x] I ran all tests on my computer and it's all green (i.e. `invoke test`).
- [x] I ran lint on my computer and there are no errors (i.e. `invoke check`).
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by chenkasirer — APPROVED** [review]
LGTM

**Comment by DomenicP** [comment]
Apologies for introducing this bug, didn't realize that `TimeoutError` was new in Python 3. It looks like this repo is already setup with GitHub Actions and a matrix for Python versions, maybe it would be helpful to add all of the Python versions for actively supported ROS distros to that matrix? I'll look into opening a follow-up PR to add this

**Comment by DomenicP** [comment]
Opened #107 if anyone is interested in a follow-up discussion for testing compatibility with Python 2.7 (and other Python 3 versions).

**Pull request merged**
